### ISSUE TITLE
Unknown __fastfail() status code: 0x0000000000000048 when using AOT.

### ISSUE THREAD

**Issue by WCKYWCKF** [wieslawsoltes/Xaml.Behaviors#11]
![image](https://github.com/user-attachments/assets/10b5defe-bbe5-4af9-af0f-d2f39106914b)

Is it because of reflection?

**Comment by wieslawsoltes** [comment]
Probably, try adding trim roots e.g. https://github.com/wieslawsoltes/Avalonia.Xaml.Behaviors/blob/6dda3ca4cc07cdcc95ccb5f0527dcd874a3b7e61/samples/BehaviorsTestApplication/BehaviorsTestApplication.csproj#L23

**Comment by WCKYWCKF** [comment]
> Probably, try adding trim roots e.g. 可能，尝试添加修剪根部，例如：
> 
> https://github.com/wieslawsoltes/Avalonia.Xaml.Behaviors/blob/6dda3ca4cc07cdcc95ccb5f0527dcd874a3b7e61/samples/BehaviorsTestApplication/BehaviorsTestApplication.csproj#L23

Failed to resolve the issue.
![image](https://github.com/user-attachments/assets/4a9a0c2a-fba2-47da-8ef6-24cd2d1234bb)

**Comment by WCKYWCKF** [comment]
Will I have this issue when publishing with AOT in BehaviorsTestApplication?

**Comment by WCKYWCKF** [comment]
Will I have this issue when publishing with AOT in BehaviorsTestApplication?

**Comment by wieslawsoltes** [comment]
Sorry but you have to properly handle trimming its not part of behaviors, you can see many warnings are present when using some behaviors as they rely on reflection but that part is beyond scope of this project and is user related csproj/mbuild configuration.
